/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_app_training_data              25
#define gattdb_feature_vector_chunk           27
#define gattdb_app_training_data_metadata     30
#define gattdb_fv_max_len                     32
#define gattdb_lv_max_len                     34
#define gattdb_fv_len                         36
#define gattdb_lv_len                         38
#define gattdb_app_machine_learning_model     39
#define gattdb_model_params                   41
#define gattdb_model                          43
#define gattdb_hyperparams                    45


#endif // __GATT_DB_H
